/**
 * Bake the RoubaAI mark into the brand client bundle.
 *
 * The sidebar and hero brand slots receive a React component, and the client
 * half is a single closure the harness loads through `window.__ModuleLoader__`:
 * it has no asset pipeline of its own, and a relative URL would resolve against
 * whatever origin the shell happens to serve. The mark is therefore embedded as
 * a data URI generated from `assets/logo.png`.
 *
 *   node packages/brand/scripts/sync-logo.mjs
 *   node packages/brand/scripts/sync-logo.mjs --check   # fail on drift, write nothing
 *
 * The generated module is committed, so the package builds without this script,
 * and `--check` is what catches an asset that was swapped without re-running it.
 *
 * @module roubaai-media/scripts/sync-logo
 */

import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(packageRoot, 'assets', 'logo.png')
const target = join(packageRoot, 'src', 'client', 'logo.ts')

const png = readFileSync(source)
const dataUrl = `data:image/png;base64,${png.toString('base64')}`
const digest = createHash('sha256').update(png).digest('hex')

const contents = `/**
 * The RoubaAI mark, embedded as a data URI.
 *
 * Generated by scripts/sync-logo.mjs from assets/logo.png (sha256 ${digest}).
 * Change that file and re-run the script instead of editing this one: the brand
 * slots render this directly, and the client half has nowhere to fetch an image
 * from.
 *
 * @module @roubaai/brand/client
 */

/** The RoubaAI mark as a data URL the brand slots render as an image. */
export const ROUBA_LOGO_DATA_URL =
  '${dataUrl}'
`

const shown = relative(packageRoot, target).split('\\').join('/')

if (process.argv.includes('--check')) {
  if (!existsSync(target) || readFileSync(target, 'utf8') !== contents) {
    throw new Error(`${shown} is stale: the embedded mark no longer matches assets/logo.png (run sync:logo)`)
  }
  console.log(`sync-logo: ${shown} matches assets/logo.png (sha256 ${digest.slice(0, 12)})`)
} else {
  writeFileSync(target, contents)
  console.log(
    `sync-logo: ${String(png.length)} bytes (sha256 ${digest.slice(0, 12)}) -> ${shown}, ${String(dataUrl.length)} chars`,
  )
}
